version: '3.3'
services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'orders'
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  order-service:
    image: com.interview.codepole/order-service:0.0.1
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  my-db: